<?php

return [
    /*
    | Catégories catalogue pharmacie (référentiel métier).
    | Utilisées au seed et pour enrichir les tenants existants.
    */
    'names' => [
        'Antalgiques (contre la douleur)',
        'Antipyrétiques (contre la fièvre)',
        'Anti-inflammatoires (AINS)',
        'Antibiotiques',
        'Antifongiques',
        'Antiviraux',
        'Antipaludiques',
        'Antiparasitaires',
        'Anthelminthiques (contre les vers)',
        'Antituberculeux',
        'Antihistaminiques (allergies)',
        'Antiasthmatiques',
        'Bronchodilatateurs',
        'Antitussifs (contre la toux)',
        'Expectorants / Mucolytiques',
        'Décongestionnants nasaux',
        'Antiulcéreux',
        'Antiacides',
        'Antidiarrhéiques',
        'Laxatifs',
        'Antispasmodiques',
        'Antiémétiques (nausées et vomissements)',
        'Antidiabétiques',
        'Insulines',
        'Antihypertenseurs',
        'Diurétiques',
        'Antiarythmiques',
        'Anticoagulants',
        'Antiagrégants plaquettaires',
        'Hypolipidémiants (cholestérol)',
        'Vitamines',
        'Compléments alimentaires',
        'Minéraux et électrolytes',
        'Corticoïdes',
        'Immunostimulants',
        'Immunosuppresseurs',
        'Hormones',
        'Contraceptifs',
        'Médicaments gynécologiques',
        'Médicaments urologiques',
        'Antidépresseurs',
        'Anxiolytiques',
        'Antipsychotiques',
        'Hypnotiques / Somnifères',
        'Antiépileptiques',
        'Antimigraineux',
        'Antiparkinsoniens',
        'Dermatologiques',
        'Ophtalmologiques',
        'ORL',
        'Antiseptiques et désinfectants',
        'Solutions de perfusion',
        'Vaccins',
        'Produits dentaires',
        'Produits nutritionnels',
        'Produits pédiatriques',
        'Produits de premiers secours',
        'Matériel médical',
    ],
];
